DNAnexus archiving tool
moka-guys/dx_api_bridge pull request #1
Opened 2022-04-06 15:03 UTC by preciserobot

Added DNAnexus archiving tool and set out example use cases in README.

Review only required for `app/dx.py`, `dxarc.py`, `compute_plot.R`
All other scripts are related to the Stopping Sanger project and won't enter production.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1)

2022-04-12 16:51 UTC, Graeme-Smith approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-:-N-OEgo99EhbaCWVQh0X:bnfp4nl)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @preciserobot)

___
*[dxarc.py, line 61 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N-OFgQb1VaZpLy5y81r:-N-OFgQb1VaZpLy5y81s:bf0rps3) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L61)):*
> ```Python
> def remove_if_in_project(file_ids, project_regex):
>     pass
> ```

What is the *remove_if_in_project* function for?  Is it still required?
___
*[dxarc.py, line 69 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N-OGo_K6oi5nYOa6poW:-N-OGo_K6oi5nYOa6poX:b-ha2p9e) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L69)):*
> ```Python
>     # init progress reporter for pandas operations
>     tqdm.pandas()
> ```

Nice - I've not used the tqdm package before.
___
*[dxarc.py, line 93 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N-SSCUu0iJW6G4UENqP:-N-SSCUu0iJW6G4UENqQ:b3oer8d) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L93)):*
> ```Python
>                 data[col] = workstation['describe'][col]
>             df.append(data)
>         df.commit()
> ```

Are you using the commit() method to write this to a database? Not obvious from the code I'm reviewing what the database details are.
___
*[dxarc.py, line 129 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N-SQ1isAKtrsEFMLur1:-N-SQ1isAKtrsEFMLur2:bg7i4qd) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L129)):*
> ```Python
>                 followed_objects = []
>                 print(f'Following {len(objects)} objects into other projects...')
>                 for object in tqdm(objects):
> ```

I assume the tqdm() just provides a process bar in the command line?
___
*[dxarc.py, line 193 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N-STkZ_AhmtRiqq8FHf:-N-STkZ_AhmtRiqq8FHg:b-b182ap) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L193)):*
> ```Python
>                     if args.dryrun:
>                         print(f'Would archive {file["id"]} in {file["project"]}...')
>                     else:
> ```

Should unarchive replace archive in this print statement, as per below?



_Suggestion:_
```Python
print(f'Would unarchive {file["id"]} in {file["project"]}...')
```
___
*[dxarc.py, line 286 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N-TSdcvAsK4j7JpkJW3:-N-TSdcvAsK4j7JpkJW4:b-vrkyr8) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L286)):*
> ```Python
>             print(f'Archived size:      {sum_ark:12.3f} GB')
>             print(f'Live size:          {sum_live:12.3f} GB\n')
>             print(f'Total storage cost: ${sum_cost:10.2f}')
> ```

Not sure from the code what referencs to 12.3f and10.2f refer to ?  I assume it is just formating the numerical data in the f-string?


<!-- Sent from Reviewable.io -->

2022-05-05 14:08 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1)* status: 7 of 9 files reviewed, 13 unresolved discussions (waiting on @Graeme-Smith and @preciserobot)

___
*[`dxarc.py` line 40 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N-OQ1qn9wJTGVztqPDl:-N-OQ1qn9wJTGVztqPDm:bz1oodo) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L40)):*
> ```Python
>     def __init__(self, file, columns=None):
>         self.file = file
>         self.columns = columns
> ```

is  self.columns used?
___
*[`dxarc.py` line 41 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N-OQ-EwD_6SubjLLdgL:-N-OQ-Ex6nXyGBMdAlWo:bpvgg2w) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L41)):*
> ```Python
>         self.file = file
>         self.columns = columns
>         self.data = pd.DataFrame(columns=columns)
> ```

my pandas knowledge isn't great, what happens is columns doesn't exist? (I think default is set to none)
___
*[`dxarc.py` line 72 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N18yj3cBnMPs69pfr8h:-N18yj3cBnMPs69pfr8i:bfgj9g1) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L72)):*
> ```Python
>     # connect to DNAnexus
>     try:
>         dx = Dx(args.token)
> ```

is this a sdk function?



_Code quote:_
```Python
Dx
```
___
*[`dxarc.py` line 82 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N19RF0s4DQSx3glx5Mv:-N19RF0s4DQSx3glx5Mw:b-x0cjbv) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L82)):*
> ```Python
>     tags = args.tags.split(',') if args.tags else None
>     
>     # workstations
> ```

why are you checking this?
___
*[`dxarc.py` line 138 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N19YhmQ-ZdlJpp4OUpq:-N19YhmQ-ZdlJpp4OUpr:b-q8my3u) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L138)):*
> ```Python
>                 print(f'Added {len(followed_objects)} objects from other projects')
> 
>             # remove excluded objects
> ```

projects?? (not critical)



_Code quote:_
```Python
objects
```
___
*[`dxarc.py` line 148 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N19aIKL0Toh_9YFizPG:-N19aIKL0Toh_9YFizPH:b-p3uea3) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L148)):*
> ```Python
>             projects = {}
>             fileids = set([])
>             print(f'Finding projects...',file=sys.stderr)
> ```

this will print any stderror to command line? what does the log file/output look like?
___
*[`dxarc.py` line 295 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N19_06_17SGQHqFxK6Q:-N19_06_17SGQHqFxK6R:b73r1ki) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/dxarc.py#L295)):*
> ```Python
>                 print(f'Archiving {len(projects)} projects...', file=sys.stderr)
>                 # get file ids from projects
>                 exclude_files = dx.project_file_ids(args.notin)
> ```

took me a while here - so the idea is , if a fileid is also in one of the projects identified by the --notin argument do not archive
___
*[`app/dx.py` line 327 at r1](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1#-N19ZWDFDVDKmqj963W4:-N19ZWDFDVDKmqj963W5:b-jijvc2) ([raw file](https://github.com/moka-guys/dx_api_bridge/blob/b0404b7b7928769889dfb0b5220c45ce8bbabc06/app/dx.py#L327)):*
> ```Python
>         # find project-ids whose membership is reason for exclusion from archival
>         exclude_in_project = list(map(lambda x:  x['id'], self.find_projects(project_regex, 'regexp'))) if project_regex else []
>         # find all file ids in those projects (faster than querying the projects for each archival candidate)
> ```

wouldn't all fileids be the same? could you not just return projectid:fileid?


<!-- Sent from Reviewable.io -->

2022-05-06 12:24 UTC, aledj2 approved these changes
> Reviewed 1 of 8 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1)* status: all files reviewed, 5 unresolved discussions (waiting on @Graeme-Smith)



<!-- Sent from Reviewable.io -->

2022-05-12 12:13 UTC, aledj2 approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dx_api_bridge/1)* status: all files reviewed, 5 unresolved discussions (waiting on @Graeme-Smith)



<!-- Sent from Reviewable.io -->

2022-05-13 14:29 UTC, merged